### ISSUE TITLE
Find getContext calls that have an ! in them

### ISSUE THREAD

**Issue by echeese** [Siorki/RegPack#30]
RegPack was unable to find my getContext() call because it looked like this:

```javascript
canvas.getContext('webgl', {
    antialias: !1,
    alpha: !1
})
```

It'd be nice if RegPack was able to recognize this and pull out my context.

**Comment by Siorki** [comment]
RegExp at the beginning of `preprocessWebGLContext()` has to be improved to account for '!' character.
