### ISSUE TITLE
End support for Chrome <41

### ISSUE THREAD

**Issue by Siorki** [Siorki/RegPack#32]
Issue #20 focused on ironing out the differences between browsers.
Chrome initially implemented a method `context2D.getImageFromRect()` that has since been deprecated, then phased out in Chrome 41. Safari is the [only major browser](http://compatibility.shwups-cms.ch/de/home?&property=CanvasRenderingContext2D.prototype.drawImageFromRect) still supporting it.

The existence of  `getImageFromRect()` affects the canvas method hashing algorithm within RegPack. The best faring hashing functions (usually `c[0]+[c[6]]`or `c[2]+[c[4]]`) do not distinguish between `getImage()`and `getImageFromRect()`, so to stay on the safe side, the method is not renamed inside the packed code.

Dropping the support for `getImageFromRect()` will gain 4-6 bytes in a few cases (2 entries out of 15 in the [benchmark](http://siorki.github.io/benchmarks.html) ), while losing compatibility with Safari and old versions of Chrome : code packed in another browser may not work with these.

Should it be done now ? Later ? Or left as an option for the user ?

**Comment by qfox** [comment]
Feel free to ignore it for JS1k; since the API is phased out, no two browsers will support it hence the feature would not be allowed.

**Comment by subzey** [comment]
As for me, Chrome <41 can be dropped safely. I can't imagine someone making a new demo in old browser.

About Safari… I don't know.

**Comment by Siorki** [comment]
Unfortunately, ending support has consequences even for code not using the deprecated method.

The immediate impact is that a demo packed on any browser not implementing the method (FF, Chrome 41+, ...) might not work under Chrome <41 and Safari if it uses ``drawImage()``.

*Whether it works or not entirely depends on whether ``drawImage()`` comes before or after ``drawImageFromRect()`` upon iterating context methods ``for i in c``. The order is browser-specific and may even change from one version to another of the same browser. The reason for failing is that the browser incorrectly decode ``c.dI()`` (or whatever name the method is hashed to) as ``c.drawImageFromRect()`` instead of ``c.drawImage()``*

Code packed under Safari will still work with Safari though.

**Comment by qfox** [comment]
fwiw I retroactively fixed demo's that relied on this method where the order/api was changed by explicitly setting the keys, fixing the expected order. So far it's been possible to fix all older demos like this one way or another. I'm sure there'll be a case where I can't fix it though, but oh well. The canvas api isn't that volatile anyways.

As for this case, I don't know :) I think the canvas hack should be added by the runner, hard to get right by an automated tool. But that shouldn't stop you, of course.

**Comment by Siorki** [comment]
I'll postpone that change to v5.0 (at least), this will give a chance to see where Safari is heading regarding the deprecated method. This way RegPack will not introduce incompatibility issues in js1k 2016.

**Comment by Siorki** [comment]
`drawImageFromRect()` is absent from [Webkit API documentation](https://developer.apple.com/reference/webkitjs/canvasrenderingcontext2d) -> OK to remove
