### ISSUE TITLE
Can't install RegPack with npm3

### ISSUE THREAD

**Issue by echeese** [Siorki/RegPack#34]
When I try to install this repository as an npm package, I get the following error:

`npm: Invalid version: "4.0"`

It appears that npm (I'm using 3.3.12) requires packages to use semver.

**Comment by Siorki** [comment]
Changed to 4.0.0 in ``package.json``, let me know if this works for you.

**Comment by Siorki** [comment]
Merged pull request #35, adds definition of main file in package.json
Thanks for the fix.
