### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by gre** [Siorki/RegPack#37]
it would be great to be able to install it from npm

**Comment by gre** [comment]
and also to define a "bin" so it can work as a command

**Comment by Siorki** [comment]
You already did that in PR #40 , right ?

**Comment by gre** [comment]
#40 made it ready to have a "regpack" command, but you still need to publish to npm for each new version release with `npm publish`. That way people can do `npm install -g regpack` and have the command. That also means you'll have to bump a version and do a new npm publish everytime you want to update the published version.

**Comment by Siorki** [comment]
4.0.1 published to npm
