### ISSUE TITLE
should varsNotReassigned also includes 'g' for WebGL ?

### ISSUE THREAD

**Issue by gre** [Siorki/RegPack#39]
I can't use the CLI with WebGL, looks like the "g" gets overrided.

```js
for(_='at$tion#Loca#:lo$9,e)8g.7=7inraer1,(rttribtexAreturn );1.0vecShad($tachc,uffAry_SHADER,i=func# niformvar void ma(){gl_	Progm((7ARRAY_BUFFER,;varyg 2 uv;cre$e-requestAnima#Fme(a),7atshadSource(a,icompilear8{a,tVERTEXr;o=a;tFRAGMENTe,n=a,c7onlkcusecugetA:(c,"p"7enableV(uvPot(u,2,7FLOAT,!0,0),[c]}e8{r[e]||[e]getU:[0]8)}a){u1f(e(n,"b"),.5+.5*M$h.cos/1e3)dws(7TRIANGLES,0,6)}t="precision highp f9u f9 b;	FgColor=4(uv.x,uv.y,b,}",i="aute 2 p	Posi#=4(p,0.0,uv=0.5*(p+}",oB(7bdBobD$anew F932([--1]STATIC_DRAWn=r(i,t';g=/[-7-:#$]/.exec(_);)with(_.split(g))_=join(shift());eval(_)
```

**Comment by gre** [comment]
actually the bug is that g is in the regpack extractor and overrides the contextual g, I suggest to use 'G' instead. I'll provide it in a PR

**Comment by Siorki** [comment]
[Rules for 2016](http://js1k.com/2016-elemental/rules) mention that both 2D and 3D contexts should be in c, but the [shim](http://js1k.com/2016-elemental/shim.html) keeps the definition for `g`.

`d` should also be included in varsNotReassigned as it now contains the document. So the initialization changes from `abc` to `abcdg` .

**Comment by Siorki** [comment]
PR #41 merged, thanks for the fix

**Comment by Siorki** [comment]
Reopened - to include a default value of "abcdg" for varsNotReassigned

**Comment by Siorki** [comment]
All set - PR merged and added `d` and `g` to `varsNotReassigned`

**Comment by gre** [comment]
cool :) thanks

**Comment by Siorki** [comment]
Reopening again - I didn't notice yesterday, but the first and second compression stages also need renaming `g` to `G`.
