### ISSUE TITLE
Crusher phase - list patterns that are "almost" gains

### ISSUE THREAD

**Issue by Siorki** [Siorki/RegPack#48]
A specialization of #8.
The crusher could report patterns that were not added to the dictionary because the gain was zero or negative, but that could topple on the positive side with one more character or occurrence. The end of the info panel (after the allocated tokens) would be the right place for this.

This is interesting when attempting to refactor one's code to benefit from the entropy packing. Current example features 3 occurrences of `64` which is not enough to warrant a gain. Adding a 4th instance (or replacing another numerical value with 64) would bring the gain to 1 byte.

**Comment by xem** [comment]
Good idea! It's true, sometimes we don't know what we could change slightly to make a difference once packed

**Comment by Siorki** [comment]
Following implementation of #47, the crusher records pattern strings that were left uncompressed after the token space was used up. 

Those patterns are now shown in the info panel. When this happens, compression can be improved by freeing an extra token (and thus #8 could check on least used characters and suggest to avoid them).

Closing the issue as we now have listed : 
 - patterns that would compress if an extra token were available
 - patterns that would bring a gain if there was an extra occurrence
