### ISSUE TITLE
$ in template literals

### ISSUE THREAD

**Issue by subzey** [Siorki/RegPack#57]
Currently renaming routine incorrectly treats `$` in template literals as a variable. As a result, it is renamed.

There's an example: after passing ``alert(`${i}`)`` into RegPack, the resulting string becomes ``alert(`a{e}`)``.

That's not a big issue as the `$` may be manually excluded, but this behavior can be surprising.

**Comment by Siorki** [comment]
So far RegPack performs renaming inside strings, however I am still not convinced that it should be done that way, the only reason for it is if the string is run through `eval()` (or any equivalent). This is an open topic.

RegPack v5.0 will identify strings within the code (for #55). This issue can easily be solved by checking for `${` in template literals.
Avoiding replacement for template literals should be as easy as ckeching for `${`

**Comment by Siorki** [comment]
I went for the following strategy : the replacement is performed : 
 - outside strings
 - inside a substitution pattern `${...}` of a template string, as it is likely that variables will be mentioned there

Every other occurrence (in a string) is not replaced. I assumed that `eval()`'ing a string is an uncommon occurrence.
