### ISSUE TITLE
preprocessed field enhancements

### ISSUE THREAD

**Issue by xem** [Siorki/RegPack#68]
Hi,

Preprocessed field basically removes line breaks and the whitespaces that follow them.

But it doesn't remove trailing and leading spaces.

Also, it removes line breaks in template literals (it shouldn't).

Ex:

````
  a=`
  b
  c
  `  
````

should be preprocessed into:

````
a=`
  b
  c
  `
````

instead of 

````
  a=`bc`  
````

It should also remove trailinf spaces at the end of a line, before a line break, except if we're in an ES6 string.

And for the record, it also doesn't check if a ";" is needed on the previous line before removing a line break, but that's okay I guess. FYI here's an example:

````
a=1
b=2
````

Thanks!

**Comment by Siorki** [comment]
Closing now that #74 and #96 are fixed.
