### ISSUE TITLE
Line endings in bin/regpack

### ISSUE THREAD

**Issue by julien** [Siorki/RegPack#70]
Hi,

First thanks for this great tool.

I've had an issue on Linux (Debian stable)  and mac OS when installing regpack via npm, and it took me a while to figure it out, so although this is not very important I thought I'd share, in case it can help.

First I installed regpack globally, with 

```shell
[sudo] npm i -g regpack
```

Then tried it out

```shell
regpack input.js > output.js
#  : No such file or directory
```

***:No such file or directory** is the output and no file is created*

So I removed everything, cloned the git repository and used `npm link .` from there ... 

```shell
[sudo] npm uninstall -g regpack
```

```shell
git clone git@github.com/Siorki/RegPack.git
cd RegPack
npm i
[sudo] npm link .
```

Tried it out

```shell
regpack input.js > output.js
stats: 1897B to 1066B (-831B, -43.8%) # yay!
```

I didn't really understand what was going on, so once again .... uninstall everything

```shell
cd RegPack
[sudo] npm unlink .
```

Re-install from npm 

```shell
[sudo] npm i -g regpack
```

I wanted to check the "filetype" of the node "binary", because I've had issues with node.js, python or other scripts before between different OS's

```shell
file ~/.nvm/versions/node/v7.5.0/lib/node_modules/regpack/bin/regpack 
/home/jc/.nvm/versions/node/v7.5.0/lib/node_modules/regpack/bin/regpack: Pascal source, ASCII text, with CRLF line terminators
```

***CRLF line terminators?** Well let's change that and see what happens next*

So I decided to change that 

```shell
dos2unix ~/.nvm/versions/node/v7.5.0/lib/node_modules/regpack/bin/regpack 
dos2unix: converting file /home/jc/.nvm/versions/node/v7.5.0/lib/node_modules/regpack/bin/regpack to Unix format ...
```

And now

```shell
regpack input.js > output.js 
stats: 1897B to 1066B (-831B, -43.8%)
```

The thing is if I check the file in the repository I cloned previously, ìt doesn't show exactly the same output

```
RegPack (master) $ file bin/regpack 
bin/regpack: Pascal source, ASCII text
```

*no **CRLF** here* 

Maybe you could add this line in the [.gitattributes](https://github.com/Siorki/RegPack/blob/master/.gitattributes) to force the line endings?

```shell
bin/regpack -crlf
```

Cheers

**Comment by Siorki** [comment]
Many thanks for taking the time to investigate the issue and provide a PR !

Related read for anyone interested in the issue : GitHub article on [dealing with line endings](https://help.github.com/articles/dealing-with-line-endings/)

**Comment by Siorki** [comment]
PR #71 merged. Thanks again.
