### ISSUE TITLE
Lines using CR as separator without ; in input code break after preprocessing

### ISSUE THREAD

**Issue by noxarivis** [Siorki/RegPack#78]
i tried compressing the test script from http://www.scriptcompress.com/ (and some scripts by myself)
```
function randomSite() {
		 var websites = new Array();
				/* THIS IS OUR 1ST COMMENT TYPE */
		websites[0] = 'http://www.WHAK.com'
		websites[1] = "http://www.BibleThumper.net";
		websites[2] = "http://www.Trollize.com";
		websites[3] = "http://www.Holy-Bibles.com";
		websites[4] = "http://www.Make-A-Meme.com";
		websites[5] = 'http://www.BoobSigns.com'
		websites[6] = "http://www.SeekFreak.com"
				// THIS IS OUR 2ND COMMENT TYPE
		websites[7] = "http://www.Is-A-Jerk.com";
		websites[8] = "http://www.HolyBibleVerse.com";
		websites[9] = "http://www.HolyBibleSearch.com";
		websites[10] = "http://www.SirSeek.com";
		websites[11] = "http://www.TXT2PIC.com";
		websites[12] = "http://www.13KG.com";
		websites[13] = "http://www.Nerdful.com";
		websites[14] = "http://www.FanSignGenerator.com";
			/*
			THIS IS OUR
			3RD COMMENT
			TYPE
			*/
		websites[15] = "http://www.Holy-Bibles.org";
		websites[16] = "http://www.VirtualHolyBible.com";
		websites[17] = "http://www.ScriptCompress.com"
		websites[18] = "http://www.Holy-Bibles.com";
		websites[19] = "http://www.Make-A-Meme.com";
        <!--[[ THIS IS OUR 4TH COMMENT HTML TYPE ]]-->
        var rand = Math.floor(Math.random()*websites.length);
	return websites[rand];
};  
alert(randomSite());
```
and it results into an Uncaught Syntax Error in Chrome and firefox.

please fix it

**Comment by Siorki** [comment]
The provided code indeed compresses with RegPack, but will not execute once packed.
``eval(_)`` fails, however ``console.log(_)`` shows a code similar to the original, meaning the packing / unpacking routine seems to work properly.

On a side note, C-style comments ``/* comment */`` and xml-style comments ``<!-- comment -->`` should be discarded => new issue to open.

The reason why the unpacked code does not execute is that RegPack removed all the CR (Carriage Returns) from the original code, however some lines did not end properly with the separator ``;`` - the CR itself acted as a separator.

In this case, the proper action should be to keep one separator, either ; or CR. This is more of a [linting issue](https://www.sitepoint.com/comparison-javascript-linting-tools/) and exactly the same issue as in #74 .

**Comment by noxarivis** [comment]
@Siorki
how about that one?
http://siorki.github.io/regPack.html#code=ICAgICAgICAvLyBnZXRpbmcgY2FudmFzIGJ5IGlkIGMKICAgICAgICB2YXIgYyA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCJjIik7CiAgICAgICAgdmFyIGN0eCA9IGMuZ2V0Q29udGV4dCgiMmQiKTsKCiAgICAgICAgLy9tYWtpbmcgdGhlIGNhbnZhcyBmdWxsIHNjcmVlbgogICAgICAgIGMuaGVpZ2h0ID0gd2luZG93LmlubmVySGVpZ2h0OwogICAgICAgIGMud2lkdGggPSB3aW5kb3cuaW5uZXJXaWR0aDsKCiAgICAgICAgLy9jaGluZXNlIGNoYXJhY3RlcnMgLSB0YWtlbiBmcm9tIHRoZSB1bmljb2RlIGNoYXJzZXQKICAgICAgICB2YXIgbWF0cml4ID0gIkFCQ0RFRkdISUpLTE1OT1BRUlNUVVZXWFlaMTIzNDU2Nzg5QCMkJV4mKigpKiZeJSI7CiAgICAgICAgLy9jb252ZXJ0aW5nIHRoZSBzdHJpbmcgaW50byBhbiBhcnJheSBvZiBzaW5nbGUgY2hhcmFjdGVycwogICAgICAgIG1hdHJpeCA9IG1hdHJpeC5zcGxpdCgiIik7CgogICAgICAgIHZhciBmb250X3NpemUgPSAxMDsKICAgICAgICB2YXIgY29sdW1ucyA9IGMud2lkdGgvZm9udF9zaXplOyAvL251bWJlciBvZiBjb2x1bW5zIGZvciB0aGUgcmFpbgogICAgICAgIC8vYW4gYXJyYXkgb2YgZHJvcHMgLSBvbmUgcGVyIGNvbHVtbgogICAgICAgIHZhciBkcm9wcyA9IFtdOwogICAgICAgIC8veCBiZWxvdyBpcyB0aGUgeCBjb29yZGluYXRlCiAgICAgICAgLy8xID0geSBjby1vcmRpbmF0ZSBvZiB0aGUgZHJvcChzYW1lIGZvciBldmVyeSBkcm9wIGluaXRpYWxseSkKICAgICAgICBmb3IodmFyIHggPSAwOyB4IDwgY29sdW1uczsgeCsrKQogICAgICAgICAgICBkcm9wc1t4XSA9IDE7IAoKICAgICAgICAvL2RyYXdpbmcgdGhlIGNoYXJhY3RlcnMKICAgICAgICBmdW5jdGlvbiBkcmF3KCkKICAgICAgICB7CiAgICAgICAgICAgIC8vQmxhY2sgQkcgZm9yIHRoZSBjYW52YXMKICAgICAgICAgICAgLy90cmFuc2x1Y2VudCBCRyB0byBzaG93IHRyYWlsCiAgICAgICAgICAgIGN0eC5maWxsU3R5bGUgPSAicmdiYSgwLCAwLCAwLCAwLjA0KSI7CiAgICAgICAgICAgIGN0eC5maWxsUmVjdCgwLCAwLCBjLndpZHRoLCBjLmhlaWdodCk7CgogICAgICAgICAgICBjdHguZmlsbFN0eWxlID0gIiMwRjAiOyAvL2dyZWVuIHRleHQKICAgICAgICAgICAgY3R4LmZvbnQgPSBmb250X3NpemUgKyAicHggYXJpYWwiOwogICAgICAgICAgICAvL2xvb3Bpbmcgb3ZlciBkcm9wcwogICAgICAgICAgICBmb3IodmFyIGkgPSAwOyBpIDwgZHJvcHMubGVuZ3RoOyBpKyspCiAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgIC8vYSByYW5kb20gY2hpbmVzZSBjaGFyYWN0ZXIgdG8gcHJpbnQKICAgICAgICAgICAgICAgIHZhciB0ZXh0ID0gbWF0cml4W01hdGguZmxvb3IoTWF0aC5yYW5kb20oKSptYXRyaXgubGVuZ3RoKV07CiAgICAgICAgICAgICAgICAvL3ggPSBpKmZvbnRfc2l6ZSwgeSA9IHZhbHVlIG9mIGRyb3BzW2ldKmZvbnRfc2l6ZQogICAgICAgICAgICAgICAgY3R4LmZpbGxUZXh0KHRleHQsIGkqZm9udF9zaXplLCBkcm9wc1tpXSpmb250X3NpemUpOwoKICAgICAgICAgICAgICAgIC8vc2VuZGluZyB0aGUgZHJvcCBiYWNrIHRvIHRoZSB0b3AgcmFuZG9tbHkgYWZ0ZXIgaXQgaGFzIGNyb3NzZWQgdGhlIHNjcmVlbgogICAgICAgICAgICAgICAgLy9hZGRpbmcgYSByYW5kb21uZXNzIHRvIHRoZSByZXNldCB0byBtYWtlIHRoZSBkcm9wcyBzY2F0dGVyZWQgb24gdGhlIFkgYXhpcwogICAgICAgICAgICAgICAgaWYoZHJvcHNbaV0qZm9udF9zaXplID4gYy5oZWlnaHQgJiYgTWF0aC5yYW5kb20oKSA+IDAuOTc1KQogICAgICAgICAgICAgICAgICAgIGRyb3BzW2ldID0gMDsKCiAgICAgICAgICAgICAgICAvL2luY3JlbWVudGluZyBZIGNvb3JkaW5hdGUKICAgICAgICAgICAgICAgIGRyb3BzW2ldKys7CiAgICAgICAgICAgIH0KICAgICAgICB9CgogICAgICAgIHNldEludGVydmFsKGRyYXcsIDM1KTs=

**Comment by Siorki** [comment]
Different issue, however also related to the line break removal.
The C++-style comments sharing a line with instructions are kept, effectively commenting all the code afterwards. I factored that into #79.

Closing this issue, please open another one if you notice a different bug.
