### ISSUE TITLE
Regression in v5 - Suboptimal packing due to incorrect assumed length of escape sequence

### ISSUE THREAD

**Issue by Siorki** [Siorki/RegPack#85]
Benchmark "2014 - Flappy Dragon" run with different revisions of RegPack  : 

- v4.0.1 : 984b crushed, 994b packed (character class)
- v5.0.1 : 984b crushed, 998b packed (character class)

Digging further, the crusher phase differs, v5 shaves a few bytes off the unpacking routine using ES6 (see PR #53)

- v4.0.1 : string 904b, unpacking routine 80b. Tokens include `_`
- v5.0.1 : string 911b, unpacking routine 73b.

**Comment by xem** [comment]
(I thought you used my entry as a benchmark test :o https://js1k.com/2014-dragons/demo/1704 )

**Comment by Siorki** [comment]
Right, I keep uncompressed versions of the top 3 (or so) for each edition of js1k and use them as benchmarks, to illustrate progress among revisions of RegPack :

http://siorki.github.io/benchmarks.html

**Comment by Siorki** [comment]
Added a method `getEscapedByteLength()`,  counts 2 for character \

Flappy Dragon down to 980b crushed, 994b packed.

https://github.com/Siorki/RegPack/commit/4428a6146cd10c607f4d3fefc9d93d394758a9b9
