### ISSUE TITLE
Crusher always ignores first character when searching for patterns

### ISSUE THREAD

**Issue by xem** [Siorki/RegPack#87]
Hi,
I tried to make a silly example to show someone how RegPack works, and unfortunately I think I found a bug:

http://siorki.github.io/regPack.html#code=aGVsbG8gbXkgbmFtZSBpcyBtYXggaGVsbG8gbXkgbmFtZSBpcyBtdXg=

![image](https://user-images.githubusercontent.com/1225909/47809215-af178600-dd40-11e8-98f9-bb50eb4a3986.png)

Why does the token (~) doesn't include the letter "h" ?

```
// Regpack output
_='h~ax h~ux~ello my name is m';for(i of'~')with(_.split(i))_=join(pop());

// Optimized output (-1b)
_='~ax ~ux~hello my name is m';for(i of'~')with(_.split(i))_=join(pop());
```

**Comment by Siorki** [comment]
Guess I did not choose the right timing for releasing v5.0.2 :(

The issue seems to be with the first character. If you add anything before, the initial `h` gets prepended to the pattern.

**Comment by xem** [comment]
it's always good to release :)
And yeah, there must be a ">0" instead of a ">=0" somewhere... or a misplaced "^" in a regex ?

**Comment by Siorki** [comment]
Almost ... legacy minified code that incremented the loop variable before the comparison.

https://github.com/Siorki/RegPack/commit/2e5c410f476183ef69163347790ad7b772798df2
