### ISSUE TITLE
Canvas hashing can overwrite the "protected" variables

### ISSUE THREAD

**Issue by p01** [Siorki/RegPack#9]
I've seen RegPack generate the following hashing code

```javascript
for(c in c)c[c[0]+c[1]+[c[6]]]=c[c];
```

Obviously that doesn't work all too well. It's easy to work around in the online version of RegPack but it took me a while to catch it as my text editor also played tricks.

**Comment by Siorki** [comment]
I see how you could obtain this output yet it seems a bit uncanny. The loop variable used for the hashing code is the one that is the most frequent in loops inside the original code, in order to get the benefits of compression. Did you have a lot of occurrences of `for(c` in your code ?

I'll tweak the algorithm to skip the protected variables upon choosing the loop identifier.

**Comment by p01** [comment]
Sorry for the lack of pull request, I had a very quick look at the code and didn't figure an easy way to fix. 

Here is the code that induced this hashing loop:
```javascript
(u=function(){for(requestAnimationFrame(u),a.width=x=1023,a.height=h=x*innerHeight/innerWidth|1,H=performance.now()/15|1,c.textAlign="center",c.font="2em cursive",q=170,c.fillStyle="hsl("+q+",20%,55%)",c.fillRect(0,0,1023,h),w=555;x--;)if(s=x%3?1&H++||-1:0,c[1023&H]=x&&c[1023&H]||8+Math.random()*h/2,Y=48*Math.sin(H/511-3*Math.sin(H/511*3))+s*c[1023&H]+h/2,X=1023-x+(511-x)*Y/h,c.globalAlpha=1,q=170,s)if(q+=31&Y,c.fillStyle="hsl("+q+",55%,200%)",H%511){if(1&Y&&(c.fillStyle="hsl("+q+",55%,20%)"),c.fillRect(X+3*Math.sin(q++),Y+Math.sin(q++),1,5),c.fillRect(X+3*Math.sin(q++),Y+Math.sin(q++),1,5),c.fillRect(X+3*Math.sin(q++),Y+Math.sin(q++),1,5),c.fillRect(X+48*Math.sin(q++),Y+3*Math.sin(q++),1,1),c.fillRect(X+48*Math.sin(q++),Y+3*Math.sin(q++),1,1),c.fillRect(X+48*Math.sin(q++),Y+3*Math.sin(q++),1,1),!(H%(9+3*Math.sin(H/511/3)|1)))for(z=15&Y,z+=6,Y-=6*z,c.globalAlpha=.3;z--;)c.beginPath(),c.lineTo(X,Y),c.lineTo(X-2*z+3*Math.sin(q++),Y+6*z+3*Math.sin(q++)),c.lineTo(X+2*z+3*Math.sin(q++),Y+6*z+3*Math.sin(q++)),c.fill()}else c.fillText(["Cross browser","1kb demos","February 2015","JS1k 2015"][H/511&3],X,Y);else if(c.fillStyle="hsl("+q+",55%,2%)",c.fillRect(X,Y,1,5),c.fillRect(X,Y,5,1),Y+=2,c.fillRect(X,Y,5,1),x==w)if(X-=10,c.fillRect(X,Y,20,-10),511>x)for(c.fillRect(X,Y,10,-15),X+=15,c.fillRect(X,Y,2,-15),c.fillStyle="hsl("+q+",55%,200%)",c.globalAlpha=.3,q=H,z=9;z--;)c.fillRect(X+3*Math.sin(q++),Y-6*z+3*Math.sin(q++),z,z);else w-=15;c.globalCompositeOperation="destination-in",H=31*Math.sin(H/511/2+10)+31,H=3>H?9:H*H,c.translate(511,h/2),c.rotate(H/511+.1),c.scale(H,H),X=Y=-3,c.beginPath(),c.moveTo(X,Y),c.arc(X-2,Y+3,2,0,Math.PI/2,0),X+=2,Y+=4,c.moveTo(X,Y),c.arc(X,Y-1,1,Math.PI/2,Math.PI/2*3,1),c.arc(X,Y-3,1,Math.PI/2,Math.PI/2*3,0),X+=3,c.moveTo(X,Y),c.arc(X-2,Y-5,2,0,Math.PI/2,0),X+=2,c.moveTo(X,Y),c.lineTo(X,Y-6),X+=3,c.moveTo(X,Y),c.arc(X-1,Y-2,1,Math.PI/2*3/2,Math.PI/2*3,0),c.stroke()})();
```

It's an uglified version of the [script](https://gist.githubusercontent.com/p01/c66d209fdb74514a2f00/raw/23e491abfca6ad64b1c78ef78da8a373e8130658/test.js) of my [invitation for JS1k 2015](http://www.p01.org/releases/JS1K_2015_invit/js1k_invit.htm)

There are 3 `for` loops, which all start with a different character e.g. `for(requestAnimationFrame(u)`, `for(z=15&y,z+=6,` and `for(c.fillRect(X,Y,10,-15),`

RegPack's preprocess report say:

```
Loop variables :
c *1 <-- selected
r *1
z *1
```

Not exactly the kind of code I'd write by hand, especially when optimizing for a packer, but I was short on time and the RegPack'ed Uglified code was 10-15 smaller than the RegPak'ed minified code.

**Comment by Siorki** [comment]
One of each `c`, `r` and `z`, so there is a tie for the most frequent and RegPack picks the first one in alphabetical order. All right, I can fix the issue easily, however I won't have time for that before next week.

**Comment by Siorki** [comment]
Code provided by p01 added as a test case.
Issue fixed by pull request - thanks !
3.0.2 to be pushed to online version once issue #11 is fixed.
