### ISSUE TITLE
Refactor crusher to move the initial lookup out of the main loop - speed optimization

### ISSUE THREAD

**Issue by da0ka** [Siorki/RegPack#92]
regPack.js
line 64: its variable should be local variable.
line 173-198 be able to inserted to line 168-169. So line 172,199,204 may be removed.
if line 224-226 is changed like below, line 200-203 is also unnecessary.

var newMatches={};
for(x in matches)x=x.split(e).join(c),x.length>1&&(i=s.split(x).length,i>2&&(newMatches[x]=i-1));
matches=newMatches;

**Comment by da0ka** [comment]
s = this.stringHelper.matchAndReplaceAll(s, false, e, c, "", c+e, 0, transform);
packerData.matchesLookup.push({token:c, string:e, originalString:e, depends:'', usedBy:'', gain:M, copies:N, len:bestLength, score:bestValue, cleared:false, newOrder:9999});
details+=c.charCodeAt(0)+"("+c+") : val="+bestValue+", gain="+M+", N="+N+", str = "+e+"\n";
// update the other matches in case the selected one is a substring thereof
var newMatches={};
for(x in matches)x=x.split(e).join(c),x.length>1&&(i=s.split(x).length,i>2&&(newMatches[x]=i-1));
matches=newMatches;

**Comment by Siorki** [comment]
I see. You apply token compression to the matches, then count occurrences of those matches, all in the same loop. Thus the initial redundance lookup can be entirely moved before the outer loop.

It will probably make the code structure a bit clearer and pave the way for #7 (I intend to push the redundance lookup in a separate function). You mention a speed gain, did you measure it ?

**Comment by Siorki** [comment]
First experimentations with the modified loop (initial lookup performed before, update done in a single stage) show a speed improvement of ~4% on the total processing time (preprocess + crusher + packer) over the whole benchmark set.

I'll take the opportunity to improve the readability of that section too. No need to keep minified code here.

**Comment by Siorki** [comment]
https://github.com/Siorki/RegPack/commit/739f51fa3841e12fe50eab88187bd4b8f861a421 Moved the initial lookup above the main loop
https://github.com/Siorki/RegPack/commit/cad0a0e206d436be1c2ad6c95196ab51ad4a68e9 Code cleanup and variable renaming
Interestingly, that last commit fixed a bug that was yet unknown : the last token in the list was ignored by the crusher, even though there were remaining matches. The packer was not affected and could use that last token.
Rewriting the construction of the token list with more explicit code got rid of that boundary condition.
